### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Tommaso-n**
Renamed various fields as they shadowed builtin methods.
Bumped version to 0.2.2

### CODE REVIEW

**Comment by andreroggeri** [comment]
Hey @Tommaso-n please wait for review before merging PRs.


Why this change was needed ?

**Comment by Tommaso-n** [comment]
Ok, sorry.
I'm going to write all the missing requests and responses and as i was checking the existing code, the linter reported that many field names were overwriting existing methods. I've simply renamed them

**Comment by andreroggeri** [comment]
I see, but you dont need to change the property name, just the method implementation becase it can shadow the native methods like `id` and `format`.

image

If we change just the inner impementation (Where it should be changed) there will be no breaking change for the library users.

**Comment by Tommaso-n** [comment]
I see. do you want me to make the changes as you explained to me?

**Comment by Tommaso-n** [comment]
Before I make any more unintentional mistakes, is there any reason why some classes are duplicated?
For example the Account class in account.py and accounts.py.
Can I define them in one script and import them into the other?

**Comment by andreroggeri** [comment]
Yes, we should avoid to break the compatibility with our users.

Right now we still on pre-release versioning, but I think this change is
unnecessary and will break for some users. We can still change the internal
implementation where the IDE complains about shadowing.

Em ter, 25 de ago de 2020 19:01, Tommaso-n <notifications@github.com>
escreveu:

**Pull request merged**
