### PR TITLE
Fix issue with goal_type being mapped to note for categories when using the budget detail endpoint

### PR DESCRIPTION
**Pull request by birdwing**
This is a fix for issue #102

### CODE REVIEW

**Comment by andreroggeri** [comment]
Thanks !

**Comment by birdwing** [comment]
No worries.
I loaded this up as my own package into home assistant.
And it is still pulling the note in "goal_type"

Is there anywhere else that this mapping could be wrong?
It could just be an issue with cacheing.

**Comment by andreroggeri** [comment]
Its been some time that I dont contribute to this package.

From what I looked up this change is correct.

I'll merge and generate a new version so you can check it again

**Comment by andreroggeri** [comment]
0.3.0 is released on pypi.

Can you please check ?

**Comment by birdwing** [comment]
Yes that did it!
Thank you.

**Pull request merged**
