### PR TITLE
Added update_transaction method

### PR DESCRIPTION
**Pull request by Tommaso-n**

### CODE REVIEW

**Comment by andreroggeri** [comment]
Not related to this change, but maybe the CachedClient should extend from the DefaultClient, since we just override the `get` method.

**Comment by Tommaso-n** [comment]
> The code is looking good, can you please update the README with this change ? (Updating transactions is now supported)

Done

**Comment by Tommaso-n** [comment]
> Not related to this change, but maybe the CachedClient should extend from the DefaultClient, since we just override the `get` method.

Sounds good...i'll push the changes soon

**Comment by andreroggeri** [comment]
Ok, you can do the improvement on another PR, I'll merge this one ! 👍 

Thanks for your contribution !

**Pull request merged**
