### PR TITLE
added update transaction api

### PR DESCRIPTION
**Pull request by dmlerner**
I need this additional endpoint for https://github.com/dmlerner/ynabamazonparser
Perhaps worth noting that the YNAB api does not support transactions with subtransactions in this endpoint, even though their model says it should.

### CODE REVIEW

**Comment by andreroggeri** [comment]
Hi @dmlerner thanks for your contribution.

Can you cover these changes with tests ?

**Comment by dmlerner** [comment]
I'm not sure how to actually run the tests, but this seems like it might be correct. I tried python3.7 -m unittest from the root (which contains /test). That gives me:

`
======================================================================
ERROR: ynab_sdk (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: ynab_sdk
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/mnt/c/Users/david/Dropbox/scripts/python-ynab-sdk/ynab_sdk/__init__.py", line 1, in <module>
    from ynab_sdk.ynab import YNAB
  File "/mnt/c/Users/david/Dropbox/scripts/python-ynab-sdk/ynab_sdk/ynab.py", line 1, in <module>
    from ynab_sdk.api.accounts import AccountsApi
  File "/mnt/c/Users/david/Dropbox/scripts/python-ynab-sdk/ynab_sdk/api/accounts.py", line 1, in <module>
    from ynab_sdk.api.models.responses.account import AccountResponse
  File "/mnt/c/Users/david/Dropbox/scripts/python-ynab-sdk/ynab_sdk/api/models/responses/account.py", line 4, in <module>
    from ynab_sdk.utils import parsers
  File "/mnt/c/Users/david/Dropbox/scripts/python-ynab-sdk/ynab_sdk/utils/parsers.py", line 4, in <module>
    import dateutil.parser
ModuleNotFoundError: No module named 'dateutil'
`

And 8 similar errors. I get the same on master. Any tips for running the tests?

**Comment by andreroggeri** [comment]
Tests are run with nose2.
If you installed both requirements.txt and requirements-test.txt all you gotta do is run `nose2 - v` in the root fit (maybe I should add this to the readme)

**Comment by dmlerner** [comment]
Thanks for the update. I'm actually going to abandon the branch. I found a way to generate the api from swagger that is more complete.

**Pull request closed without merging**
